# src/Ais/TranskripBundle/Resources/config/validation.yml
Ais\TranskripBundle\Entity\Transkrip:
    properties:
        nama:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
