<?php

namespace Ais\TranskripBundle\Repository;

/**
 * TranskripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranskripRepository extends \Doctrine\ORM\EntityRepository
{
}
